### ISSUE TITLE
Project: Spring Cleaning

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-ios#1067]
### Spring Cleaning

- [x] [Update Designs for Information Sheet](https://github.com/Automattic/simplenote-ios/issues/1061), https://github.com/Automattic/simplenote-ios/issues/1061
- [x] [Condensed Mode: Minimum Height](https://github.com/Automattic/simplenote-ios/issues/1045), https://github.com/Automattic/simplenote-ios/issues/1045
- [x] [Nü Tags Edition Mode](https://github.com/Automattic/simplenote-ios/issues/1042), https://github.com/Automattic/simplenote-ios/issues/1042
- [x] [Refresh: Tags Editor](https://github.com/Automattic/simplenote-ios/issues/990), https://github.com/Automattic/simplenote-ios/issues/990
- [x] [Nü Passcode](https://github.com/Automattic/simplenote-ios/issues/761), https://github.com/Automattic/simplenote-ios/issues/761
- [x] [Refresh: Editor Metrics](https://github.com/Automattic/simplenote-ios/issues/480), https://github.com/Automattic/simplenote-ios/issues/480
- [x] List: Update Sort Bar #1159

The following should be shipped as one feature:
- [x] Move New Note Button to the bottom toolbar in the list and editor: #1044
- [x] [List: Multiple Selection Support](https://github.com/Automattic/simplenote-ios/issues/1043), https://github.com/Automattic/simplenote-ios/issues/1043

Issues:
- [x] Tags Editor: RTL support https://github.com/Automattic/simplenote-ios/pull/1149#issuecomment-779874151 #1160
- [x] Tags Editor: Add tags field should stay on screen https://github.com/Automattic/simplenote- ios/pull/1149#issuecomment-779874151 #1160

Design project thread: p2XJRt-1dQ

**Comment by charliescheer** [comment]
All of the tasks on this are finished, so I am going to close it
