### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#1086]
### Details:
- [x] Simperium's JSONStorage support #1091
- [x] Simperium Support to sync current Verification State #1091
- [x] Create “Review You Account” screen #1089
- [x] Create “Verify Your Email” screen #1089
- [x] Show “Review You Account” on app launch if user is not verified and verification was not requested
- [x] Show “Verify Your Email” if verification was requested
- [x] Wire up the call to verification endpoint from “Review You Account” and “Verify Your Email” screens
- [x] Open `app.simplenote.com/settings` in a browser if user clicks on “Change Email”
- [x] Analytics

### Mockups:
<img width="300" src="https://user-images.githubusercontent.com/1195260/104479597-60153e80-55a2-11eb-8446-5aedc7cbdf8e.png"> <img width="300" src="https://user-images.githubusercontent.com/1195260/104479603-62779880-55a2-11eb-905b-4da5d83f9c7e.png">

**Comment by pachlava** [comment]
Verified all mentioned PRs that are UI-testable. iPhone XR | iOS 14.3 | SN 4.31
