### ISSUE TITLE
Project: In App Notifications - Implement NoticeView UI

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#1177]
### Details:

- [x] Create view xib and classes (NoticeView, NoticeAction) #1185 
- [x] add support for dark mode #1185
- [x] add support for dynamic type #1185 
- [x] add support for VoiceOver #1185 

Screenshot
<img src="https://user-images.githubusercontent.com/1195260/96787162-af930680-13c7-11eb-84e4-5c1fb6344b5d.gif" >
