### ISSUE TITLE
Project: In App Notices Project To Do List

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#1180]
This issue is a project outline for implementing In App Notifications as described in issue #938 

### What
Tasks:
- [x] Create UI for notice views #1177
- [x] Create Presenter/Controller classes for delivering notifications #1178
- [x] Connect Notice classes and Simplenote to display list of notices #1179

Issues:
[In App Notifications](https://github.com/Automattic/simplenote-ios/issues/938)
