### ISSUE TITLE
Wrong keyword highlighted when searching in a checklist

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1282]
### Expected
During search, the keyword that we search for should be highlighted.

### Observed
When searching in a checklist, highlighting is broken:

https://user-images.githubusercontent.com/73365754/118772701-b6fe8d80-b88c-11eb-8006-549abcbe93f7.MP4

### Reproduced
1. Create a note with this content:
```
Checklist

- [ ] 2014: (78): Dibya Shankar Mishra(BJD)
- [ ] 2009: (78): Gobardhan Dash (Congress)
- [ ] 2004: (98): Himanshu Shekhar Meher (BJP)
- [ ] 2000: (98): Himanshu Shekhar Meher (BJP)
- [ ] 1995: (98): Bikram Keshari Deo (BJP)
- [ ] 1990: (98): Bikram Keshari Deo (BJP)
- [ ] 1985: (98): Bikram Keshari Deo (Janata Party)
- [ ] 1980: (98): Maheshwar Barad (Congress-I)
- [ ] 1977: (98): Maheshwar Barad (Congress)
- [ ] 1974: (98): Udit Pratap Deo (Swatantra Party)
- [ ] 1971: (92): Trinath Sarab (Swatantra Party)
- [ ] 1967: (92): Maheswar Naik (Swatantra Party)
- [ ] 1961: (37): Maheswar Naik (Ganatantra Parishad)
- [ ] 1951: (20): P. K. Deo (Ganatantra Parishad)
```
2. Search for `bikram`
3. Open the note, navigate through matches

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.4.2|4.36.0.0

**Comment by msilbers** [comment]
reported in 4667817-zen, also using checkboxes
Simplenote v4.47
iOS v15.2

**Comment by mdrockwell** [comment]
I believe I have another case of this:
Simplenote v4.55
9593760-zd-a8c
