### ISSUE TITLE
Project: Widgets

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#1289]
This is a project post for adding iOS 14 style widgets to Simplenote.  

### Tasks

- [x] New Note Widget
- [x] Single Note Widget
- [x] Note List Widget

### Description

There are three different widgets we want to add to Simplenote.  The first is a new note button that can live on the home screen of an iPhone. This widget is only available in the smallest widget family, so the entire widget will open up into a new note.

<img src="https://cdn-std.droplr.net/files/acc_593859/eCLMhS" />

The next widget is a single note widget that displays the content of a user selected note on the home screen.  This widget is available in Small and Medium widget families.  Tapping on this widget will take the user into the selected note

<img src="https://cdn-std.droplr.net/files/acc_593859/xQ1Stc" />

<img src="https://cdn-std.droplr.net/files/acc_593859/nh6IOk" />

Lastly we have a widget that shows a list of notes in a tag.  This multiple tap targets, and will provide a shortcut into the notes that are listed.  This widget is available in medium and large widget sizes.

<img src="https://cdn-std.droplr.net/files/acc_593859/IlydIZ" />

<img src="https://cdn-std.droplr.net/files/acc_593859/COcZj8" />

**Comment by hardevine** [comment]
👍  waiting for it
