### ISSUE TITLE
Simplenote Sustainer

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#1491]
### Tasks
- [x] Implement Become a Sutainer UI
- [x] Implement Sustainer UI
- [x] Build support to store the current subscription level (Simperium-Y)
   - [x] subscribed_date (Timestamp)
   - [x] subscription_platform  (String)
   - [x] subscription_level  (String / "sustainer")
- [x] Build IAP Support
- [x] Support multiple price points
- [x] Tracks
- [x] Dismiss Sidebar's Banner when in Sustainer Mode
- [x] Review AppStoreConnect Settings?
- [x] Verify Refunds are correctly processed
- [x] Verify Interop with Android / Electron
- [ ] Bug: Sidebar didn't refresh immediately after a remote change came thru. Required a Close / Reopen!

### Design
<img width="600" alt="Screenshot 2022-10-25 at 12 31 00 PM" src="https://user-images.githubusercontent.com/1195260/197817345-060ae586-d12d-418f-a081-71b0168b35cf.png">
<img width="289" alt="Screenshot 2022-10-25 at 12 31 23 PM" src="https://user-images.githubusercontent.com/1195260/197817359-17580064-9b1b-43f0-b6ac-dd89f018e507.png">
