### ISSUE TITLE
Master List: iOS Shortcut improvements

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-ios#1566]
We are going to update the Simplenote iOS shortcuts to use the modern system APIs and to extend their functionality. 

Tasks:

- [x] Remove existing shortcuts #1567 
- [x] Re implement the existing shortcuts with the app intents API #1568 
- [x] extend shortcuts using App intents API #1569 
- [x] explore Siri integration #1570

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by charliescheer** [comment]
Marking this project as complete
