### ISSUE TITLE
Refresh: Color Scheme

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#478]
### Tasks
- [x] TableView's Backgrounds
- [x] Dark Mode Refresh
- [x] Fix Search Highlight color (in dark mode it's impossible to notice!)
- [x] Note List Highlight / Selected colors
- [x] Logout Overlay Spinner (white overlay?)
- [x] Launch Screen in Dark Mode

**Comment by jleandroperez** [comment]
Moving the **Nuke VSTheme** task over to the main Tech Debt issue (#481).

Closing this one since it's officially done!
