### ISSUE TITLE
SidebarContainer Updates

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#479]
### Tasks
- [ ] Notes List should always be visible on the iPad.
- [ ] The note Editor should have a new button which should allow us to collapse the notes list.
- [ ] Implement Blur in the NavigationBar

**Comment by NeedsAdjustment** [comment]
Any update on this? Seems fairly trivial to implement.

**Comment by jleandroperez** [comment]
It's in the roadmap, but I'm afraid we don't have a timeline at the moment.

Thank you for reaching out @NeedsAdjustment !

**Comment by egid** [comment]
It's been a while, any updates? Doesn't look like the iOS app is seeing much activity lately.

**Comment by adamjohndaly** [comment]
Seeing an issue with the keyboard and being able to scroll in an entry when SN is the smaller window in split screen on iPad. Copy and Paste work, but you cannot scroll down in the entry. 

https://user-images.githubusercontent.com/18173779/204889539-ae7b9012-5516-4b81-adb0-b317249aa989.mov

5737029-zd-woothemes
