### ISSUE TITLE
Refresh: Editor Metrics

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#480]
### Tasks
- [ ] Left + Right Padding (20pt). Nuke *noteSidePadding*
- [ ] Editor: Left and Right margins please!
- [ ] Maximum width TBD
- [ ] Fonts: Body: can we use a multiplier? (should be 24) / Title: title3

**Please validate these changes with Sly before proceeding!**

**Comment by ylor** [comment]
If possible I’d like to request support for iOS 13’s built-in font support. Or at the very least an option for a monospace face. 

Thank you for your work! So glad to see Simplenote getting some love.

**Comment by jleandroperez** [comment]
Hello there @ylor!

We're using semantic System's font (so it should adapt to your phone's accessibility settings all over!). There shouldn't be any custom fonts anywhere, may I ask you if you're experiencing any glitch with this?

Thank you for your feedback!!

**Comment by ylor** [comment]
No glitching. Just a request as part of the refresh.

iOS 13 brought first-class support for [custom fonts](https://developer.apple.com/videos/play/wwdc2019/227/) and I'd love for Simplenote to allow for it. If not, I would at the very least LOVE to have a monospace font option.

**Comment by jleandroperez** [comment]
Ahhh I see, you mean custom fonts. We do have an issue for it #32, I'm afraid **for the moment** is low priority, we've got a ton of improvements in the pipeline, so I'm afraid there is no clear timeline for it.

Nevertheless, it's definitely on the radar.

Thank you for stepping by @ylor! Have an epic day over there!

**Comment by ylor** [comment]
Thank you for the response @jleandroperez. I understand that it would be a lot of work and would definitely not expect it in the short term, but a simple preference toggle between System font (San Francisco) or System Monospace font (Menlo), would do a lot for me.

Thanks for reading.

**Comment by eshurakov** [comment]
Closing this one as it seems it is already done.

**Comment by jleandroperez** [comment]
Thank you Evgeny!!
