### ISSUE TITLE
Tech Debt: Master Issue

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#481]
### Tasks
- [ ] Implement (new) Height Calculation mechanism. Top Spacing: 12 + 22 + 1 + 20 + 20 + 13
- [ ] NoteTableViewCell: Replace UITextView(s) with UILabels. Ref. #427
- [ ] Optimize **SPTransitionController**: Generate animationOptions just once. Improve code readability **please**
- [ ] When editing the tag name, the edition was terminated when space is pressed. This seems to be by design, but I found it a bit counter-intuitive. Maybe starting/creating a new tag, or just doing nothing on space key press would be more appropriate.
