### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#507]
### Task: Data Model
- [x] Simperium bucket for recent search results (last 5 searches)

### Task: ResultsController
- [x] Encapsulate NSFetchedResultsController
- [x] Implement ResultsController <> UIKit bridge

### Task: NoteListController: State.results
- [x] Interact only with Note entities, single section

### Task: NoteListController: State.search
- [x] Interact with Notes and Tags entities
- [x] Limit the number of Tags to 5 entries
- [x] Keywords containing `tag:xxx` should filter notes containing such tag

### Task: List Interface
- [x] Replace FRC with NoteListController
- [x] NoteTableViewCell: Update Pinned and Shared Indicators location
- [x] New UITableViewCell for Tag Entities
- [x] Pressing over any `Tag` entity prefills the SearchBar with `tag:xxx`
- [x] When Search is active: dismiss the keyboard as soon as the user starts scrolling
- [x] Row Separators
- [x] Dismiss keyboard whenever **Search** is pressed
- [x] Deleting the Search Keyword should display the notes that were onscreen pre-search
- [x] Updating Search Keywords should always scroll to the top of the table
- [x] SearchBar: Restore Autocapitalization
- [x] Search should **Respect Condensed Mode Settings**
- [x] Swipeable Actions + 3d Touch: Only available for Notes (in Results or Search Mode)
- [x] SearchBar should be hidden when visualizing the Trash
- [x] Remove custom transition from List <> Editor
- [x] Highlighted Search Match's BG
- [x] Empty States: 
  - [x] **No Results**
  - [x] **No Notes**

### Task: SortBar
- [x] Note List should display the date relevant to the selected Sort Mode, when appropriate.
- [x] Location always fixed at the bottom. Shouldn't react to keyboard events.
- [x] Pressing the Sort Bar should display an Alert Sheet with the available options.
- [x] Switching Sort Order should automatically set the default order for the given "sort type".
   ```
   Arrow pointing up is A-Z
   Arrow point down is Z-A
   Default order should be A-Z
   Arrow pointing up is Oldest to newest
   Arrow pointing down is Newest to oldest
   Default order should be Newest to oldest
   ```

### Bugs:
- [x] Search Mode's Navigation Bar doesn't remain hidden, whenever you dismiss the Editor #610
- [x] Note List TableViewCell Layout Glitch (see comments in #586)
- [x] Keyboard First Responder #600 
- [x] Note List Cell Highlight Glitch
- [x] Entering Search causes the first row to jump
- [x] Keyboard Insets #603
- [x] Keyboard Style #599 
- [x] Swipe back to List may cause (THE) Keyboard glitch (w/ Search Active) #616
- [x] Dismissing Search Mode in the Editor does not dismiss Search Mode in the List #618
- [x] Rows Jumping when entering Search Mode (and we're not on top)
- [x] Single Line Glitch #522
- [x] Section Header Warning #652 
- [x] Pinned state should not be respected when searching #654
- [x] the “reverse sort order” button shouldnt do anything to the tags in search #654
- [x] Shared Indicator Animation Glitch #657
- [ ] Empty State + iPhone 5s landscape [Ref Here](https://github.com/Automattic/simplenote-ios/pull/635#pullrequestreview-357646680)

**Comment by jleandroperez** [comment]
Closing this one since it's feature complete // fully implemented. Addressing pendings as bugfixes.

**Thank you** 🔥

**Comment by bummytime** [comment]
Thank you **so much** for all your hard work on this @jleandroperez. Awesome job!!

**Comment by jleandroperez** [comment]
Thanks a lot @bummytime !!! This one would have never happened without your help, soooo EPIC team work!!!!
