### ISSUE TITLE
Release builds Master Issue

### ISSUE THREAD

**Issue by loremattei** [Automattic/simplenote-ios#661]
**Goal**: the goal of this project is to run beta and final release builds on CI with automatic upload to the stores.

Steps:

- [ ] Update the release tooling to properly handle the release finalization -> https://github.com/Automattic/simplenote-ios/pull/660.
- [ ] Update the release tooling to create the GitHub release.
- [ ] Run the build for beta releases on CI.
- [ ] Run the build for the final release on CI.
